export default [
    {
        id: 0,
        name: 'Join',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi saepe illo maiores illum harum laudantium.',
        image: 'images/projects/join.png',
        tags: ['javascript', 'backend', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
    {
        id: 1,
        name: 'Portfolio 2022',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi saepe illo maiores illum harum laudantium.',
        image: 'images/projects/portfolio.png',
        tags: ['threejs', 'javascript', 'svg', 'glsl', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
    {
        id: 2,
        name: 'The Essence of a Penguin',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi saepe illo maiores illum harum laudantium.',
        image: 'images/projects/penguin.png',
        tags: ['react', 'r3f', 'svg', 'javascript', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
    {
        id: 3,
        name: 'Sharkie',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi saepe illo maiores illum harum laudantium.',
        image: 'images/projects/sharkie.png',
        tags: ['javascript', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
    {
        id: 4,
        name: 'Pokedex',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi saepe illo maiores illum harum laudantium.',
        image: 'images/projects/pokedex.png',
        tags: ['javascript', 'api', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
]