export default [
    {
        id: 0,
        name: 'IUCN Redlist',
        description: 'A redesign of the <a href="https://www.iucnredlist.org/" target="_blank">IUCN</a> Redlist website',
        image: 'images/projects/iucn.png',
        tags: ['react', 'r3f', 'api', 'javascript', 'html', 'css'],
        alt: 'work in progress portfolio project',
    },
    {
        id: 1,
        name: 'Join',
        description: 'Group managment tool to optimize workflows',
        image: 'images/projects/join.png',
        tags: ['javascript', 'backend', 'html', 'css'],
        liveview: 'https://join.david-hckh.com/',
        github: 'https://github.com/davidhckh/join',
        alt: 'Group management tool to optimize workflows portfolio project',
    },
    {
        id: 2,
        name: 'Sharkie',
        description: 'JavaScript based jump-and-run game',
        image: 'images/projects/sharkie.png',
        tags: ['javascript', 'html', 'css'],
        liveview: 'https://sharkie-game.vercel.app/',
        github: 'https://github.com/davidhckh/sharkie-game',
        alt: 'javascript based jump-and-run game portfolio project',
    },
    {
        id: 3,
        name: 'Portfolio 2022',
        description: `The page you are looking at right now`,
        image: 'images/projects/portfolio.png',
        tags: ['threejs', 'javascript', 'svg', 'html', 'css'],
        github: 'https://github.com/davidhckh/portfolio-2022',
        alt: 'david heckhoff portfolio project 2022 threejs blender 3d design',
    },
    {
        id: 4,
        name: 'Pokedex',
        description: 'A collection and description of all 898 Pokémon',
        image: 'images/projects/pokedex.png',
        tags: ['javascript', 'api', 'html', 'css'],
        liveview: 'https://js-pokedex-virid.vercel.app/',
        github: 'https://github.com/davidhckh/pokedex',
        alt: 'pokedex design detailed design portfolio project',
    },
]