export default [
    {
        id: 0,
        name: 'Join',
        description: 'Group managment tool to optimize workflows',
        image: 'images/projects/join.png',
        tags: ['javascript', 'backend', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh/join',
    },
    {
        id: 1,
        name: 'Portfolio 2022',
        description: `Isn't that the page you are looking at right now?`,
        image: 'images/projects/portfolio.png',
        tags: ['webgl', 'javascript', 'svg', 'html', 'css'],
        liveview: 'https://david-hckh.com/',
        github: 'https://github.com/davidhckh/portfolio-2022',
    },
    {
        id: 2,
        name: 'The Essence of a Penguin',
        description: 'Work in progress',
        image: 'images/projects/penguin.png',
        tags: ['react', 'r3f', 'svg', 'javascript', 'html', 'css'],
        liveview: 'https://www.google.com/',
        github: 'https://github.com/davidhckh',
    },
    {
        id: 3,
        name: 'Sharkie',
        description: 'JavaScript based jump-and-run game',
        image: 'images/projects/sharkie.png',
        tags: ['javascript', 'html', 'css'],
        liveview: 'https://sharkie-game.vercel.app/',
        github: 'https://github.com/davidhckh/sharkie-game',
    },
    {
        id: 4,
        name: 'Pokedex',
        description: 'A collection and description of all 898 Pokémon',
        image: 'images/projects/pokedex.png',
        tags: ['javascript', 'api', 'html', 'css'],
        liveview: 'https://js-pokedex-virid.vercel.app/',
        github: 'https://github.com/davidhckh/pokedex',
    },
]